package com.midterm.securevpnproxy.base.compose

import androidx.compose.foundation.text.selection.TextSelectionColors
import androidx.compose.material.darkColors
import androidx.compose.material.lightColors
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class AppColorsPalette(
    val darkGrey09: Color = Color.Unspecified,
    val darkGrey08: Color = Color.Unspecified,
    val darkGrey07: Color = Color.Unspecified,
    val darkGrey06: Color = Color.Unspecified,
    val darkGrey05: Color = Color.Unspecified,
    val darkGrey04: Color = Color.Unspecified,
    val darkGrey03: Color = Color.Unspecified,
    val darkGrey02: Color = Color.Unspecified,
    val darkGrey01: Color = Color.Unspecified,

    val lightGrey01: Color = Color.Unspecified,
    val lightGrey02: Color = Color.Unspecified,
    val lightGrey03: Color = Color.Unspecified,
    val lightGrey04: Color = Color.Unspecified,
    val lightGrey05: Color = Color.Unspecified,
    val lightGrey06: Color = Color.Unspecified,
    val lightGrey07: Color = Color.Unspecified,
    val lightGrey08: Color = Color.Unspecified,
    val lightGrey09: Color = Color.Unspecified,

    val blue10: Color = Color.Unspecified,
    val blue09: Color = Color.Unspecified,
    val blue08: Color = Color.Unspecified,
    val blue07: Color = Color.Unspecified,
    val blue06: Color = Color.Unspecified,
    val blue05: Color = Color.Unspecified,
    val blue04: Color = Color.Unspecified,
    val blue03: Color = Color.Unspecified,
    val blue02: Color = Color.Unspecified,
    val blue01: Color = Color.Unspecified,
    val blueAlpha04: Color = Color.Unspecified,

    val green10: Color = Color.Unspecified,
    val green09: Color = Color.Unspecified,
    val green08: Color = Color.Unspecified,
    val green07: Color = Color.Unspecified,
    val green06: Color = Color.Unspecified,
    val green05: Color = Color.Unspecified,
    val green04: Color = Color.Unspecified,
    val green03: Color = Color.Unspecified,
    val green02: Color = Color.Unspecified,
    val green01: Color = Color.Unspecified,

    val red07: Color = Color.Unspecified,
    val red06: Color = Color.Unspecified,
    val red05: Color = Color.Unspecified,

    val orange06: Color = Color.Unspecified,
    val orange05: Color = Color.Unspecified,
    val orange04: Color = Color.Unspecified,
    val orange03: Color = Color.Unspecified,
    val orange02: Color = Color.Unspecified,
    val orange01: Color = Color.Unspecified,

    val blackAlpha01: Color = Color.Unspecified,
    val blackAlpha02: Color = Color.Unspecified,
    val blackAlpha03: Color = Color.Unspecified,
    val blackAlpha04: Color = Color.Unspecified,
    val blackAlpha05: Color = Color.Unspecified,
    val blackAlpha06: Color = Color.Unspecified,
    val blackAlpha07: Color = Color.Unspecified,
    val blackAlpha08: Color = Color.Unspecified,
    val blackAlpha09: Color = Color.Unspecified,

    val whiteAlpha01: Color = Color.Unspecified,
    val whiteAlpha02: Color = Color.Unspecified,
    val whiteAlpha03: Color = Color.Unspecified,
    val whiteAlpha04: Color = Color.Unspecified,
    val whiteAlpha05: Color = Color.Unspecified,
    val whiteAlpha06: Color = Color.Unspecified,
    val whiteAlpha07: Color = Color.Unspecified,
    val whiteAlpha08: Color = Color.Unspecified,
    val whiteAlpha09: Color = Color.Unspecified,

    val white: Color = Color.Unspecified,
    val black: Color = Color.Unspecified,
    val purple04: Color = Color.Unspecified,
)

val LocalColors = staticCompositionLocalOf { AppColorsPalette() }

val AppDarkColorsPalette = AppColorsPalette(
    darkGrey09 = AbsDarkGrey09,
    darkGrey08 = AbsDarkGrey08,
    darkGrey07 = AbsDarkGrey07,
    darkGrey06 = AbsDarkGrey06,
    darkGrey05 = AbsDarkGrey05,
    darkGrey04 = AbsDarkGrey04,
    darkGrey03 = AbsDarkGrey03,
    darkGrey02 = AbsDarkGrey02,
    darkGrey01 = AbsDarkGrey01,
    lightGrey01 = AbsLightGrey01,
    lightGrey02 = AbsLightGrey02,
    lightGrey03 = AbsLightGrey03,
    lightGrey04 = AbsLightGrey04,
    lightGrey05 = AbsLightGrey05,
    lightGrey06 = AbsLightGrey06,
    lightGrey07 = AbsLightGrey07,
    lightGrey08 = AbsLightGrey08,
    lightGrey09 = AbsLightGrey09,
    blue10 = AbsBlue10,
    blue09 = AbsBlue09,
    blue08 = AbsBlue08,
    blue07 = AbsBlue07,
    blue06 = AbsBlue06,
    blue05 = AbsBlue05,
    blue04 = AbsBlue04,
    blue03 = AbsBlue03,
    blue02 = AbsBlue02,
    blue01 = AbsBlue01,
    blueAlpha04 = AbsLightBlueAlpha04,
    green10 = AbsGreen10,
    green09 = AbsGreen09,
    green08 = AbsGreen08,
    green07 = AbsGreen07,
    green06 = AbsGreen06,
    green05 = AbsGreen05,
    green04 = AbsGreen04,
    green03 = AbsGreen03,
    green02 = AbsGreen02,
    green01 = AbsGreen01,
    red07 = AbsRed07,
    red06 = AbsRed06,
    red05 = AbsRed05,
    orange06 = AbsOrange06,
    orange05 = AbsOrange05,
    orange04 = AbsOrange04,
    orange03 = AbsOrange03,
    orange02 = AbsOrange02,
    orange01 = AbsOrange01,
    blackAlpha01 = AbsBlackAlpha01,
    blackAlpha02 = AbsBlackAlpha02,
    blackAlpha03 = AbsBlackAlpha03,
    blackAlpha04 = AbsBlackAlpha04,
    blackAlpha05 = AbsBlackAlpha05,
    blackAlpha06 = AbsBlackAlpha06,
    blackAlpha07 = AbsBlackAlpha07,
    blackAlpha08 = AbsBlackAlpha08,
    blackAlpha09 = AbsBlackAlpha09,
    whiteAlpha01 = AbsWhiteAlpha01,
    whiteAlpha02 = AbsWhiteAlpha02,
    whiteAlpha03 = AbsWhiteAlpha03,
    whiteAlpha04 = AbsWhiteAlpha04,
    whiteAlpha05 = AbsWhiteAlpha05,
    whiteAlpha06 = AbsWhiteAlpha06,
    whiteAlpha07 = AbsWhiteAlpha07,
    whiteAlpha08 = AbsWhiteAlpha08,
    whiteAlpha09 = AbsWhiteAlpha09,
    white = AbsWhite,
    purple04 = AbsPurple04,
    black = AbsBlack,
)

val AppLightColorsPalette = AppColorsPalette(
    darkGrey09 = AbsWhite,
    darkGrey08 = AbsLightGrey01,
    darkGrey07 = AbsLightGrey03,
    darkGrey06 = AbsLightGrey04,
    darkGrey05 = AbsLightGrey05,
    darkGrey04 = AbsLightGrey06,
    darkGrey03 = AbsLightGrey07,
    darkGrey02 = AbsLightGrey08,
    darkGrey01 = AbsLightGrey09,
    lightGrey01 = AbsDarkGrey08,
    lightGrey02 = AbsDarkGrey07,
    lightGrey03 = AbsDarkGrey07,
    lightGrey04 = AbsDarkGrey06,
    lightGrey05 = AbsDarkGrey05,
    lightGrey06 = AbsDarkGrey04,
    lightGrey07 = AbsDarkGrey03,
    lightGrey08 = AbsDarkGrey02,
    lightGrey09 = AbsDarkGrey01,
    blue10 = AbsBlue10,
    blue09 = AbsBlue09,
    blue08 = AbsBlue07,
    blue07 = AbsBlue06,
    blue06 = AbsBlue06,
    blue05 = AbsBlue07,
    blue04 = AbsBlue05,
    blue03 = AbsBlue04,
    blue02 = AbsBlue06,
    blue01 = AbsBlue10,
    blueAlpha04 = AbsDarkBlueAlpha04,
    green10 = AbsGreen10,
    green09 = AbsGreen09,
    green08 = AbsGreen08,
    green07 = AbsGreen06,
    green06 = AbsGreen05,
    green05 = AbsGreen07,
    green04 = AbsGreen07,
    green03 = AbsGreen08,
    green02 = AbsGreen09,
    green01 = AbsGreen10,
    red07 = AbsRed06,
    red06 = AbsRed05,
    red05 = AbsRed05,
    orange06 = AbsOrange06,
    orange05 = AbsOrange06,
    orange04 = AbsOrange05,
    orange03 = AbsOrange04,
    orange02 = AbsOrange03,
    orange01 = AbsOrange02,
    blackAlpha01 = AbsWhiteAlpha01,
    blackAlpha02 = AbsWhiteAlpha02,
    blackAlpha03 = AbsWhiteAlpha03,
    blackAlpha04 = AbsWhiteAlpha04,
    blackAlpha05 = AbsWhiteAlpha05,
    blackAlpha06 = AbsWhiteAlpha06,
    blackAlpha07 = AbsWhiteAlpha07,
    blackAlpha08 = AbsWhiteAlpha08,
    blackAlpha09 = AbsWhiteAlpha09,
    whiteAlpha01 = AbsBlackAlpha01,
    whiteAlpha02 = AbsBlackAlpha02,
    whiteAlpha03 = AbsBlackAlpha03,
    whiteAlpha04 = AbsBlackAlpha04,
    whiteAlpha05 = AbsBlackAlpha05,
    whiteAlpha06 = AbsBlackAlpha06,
    whiteAlpha07 = AbsBlackAlpha07,
    whiteAlpha08 = AbsBlackAlpha08,
    whiteAlpha09 = AbsBlackAlpha09,
    white = Color.Black,
    purple04 = AbsPurple05,
    black = AbsWhite,
)

val DarkColorPalette = darkColors(
    primary = AbsDarkGrey08,
    primaryVariant = AbsWhite,
    secondary = AbsWhite,
    secondaryVariant = AbsWhite,
    onPrimary = AbsWhite,
    onSecondary = AbsWhite,
)
val LightColorPalette = lightColors(
    primary = AbsWhite,
    primaryVariant = AbsWhite,
    secondary = AbsWhite,
    secondaryVariant = AbsWhite,
    onPrimary = AbsWhite,
    onSecondary = AbsWhite,
)

val DarkTextSelectionColors =
    TextSelectionColors(handleColor = AbsBlue06, backgroundColor = AbsDarkBlueAlpha04)
val LightTextSelectionColors =
    TextSelectionColors(handleColor = AbsBlue06, backgroundColor = AbsLightBlueAlpha04)
